version: '3'
services:

  cleaner:
    build: ./app_cleaner
    image: app_cleaner
    volumes:
      - ./raw_data:/input_data
      - ./clean_data:/output_data
      - ./mlflow_data:/mlruns

  model:
    build: ./app_model
    image: app_model
    volumes:
      - ./clean_data:/input_data
      - ./model_data:/output_data
      - ./mlflow_data:/mlruns

  mlflow:
    build: ./app_mlflow   
    image: app_mlflow
    volumes:
      - ./model_data:/input_data
      - ./mlflow_data:/mlruns




